# See https://github.com/marketplace/actions/close-stale-issues

name: Mark stale issues and pull requests

on:
  schedule:
  # run at 01:30 UTC daily
  - cron: "30 1 * * *"

permissions:
  contents: read

jobs:
  stale:
    permissions:
      issues: write  # for actions/stale to close stale issues
      pull-requests: write  # for actions/stale to close stale PRs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

        # The number of days old an issue can be before marking it stale.
        days-before-stale: 60
        # Number of days of inactivity before a stale issue is closed
        days-before-close: 30

        # If an issue/PR is assigned, trust the assignee to stay involved
        # Can revisit if these get stale
        exempt-all-assignees: true
        # Issues with these labels will never be considered stale
        exempt-issue-labels: "need: discussion,cleanup"

        # Label to use when marking an issue as stale
        stale-issue-label: 'Can Close?'
        stale-pr-label: 'Can Close?'

        stale-issue-message: >
          This issue has been automatically marked as stale because it has had no recent activity.
          It will be closed if no further activity occurs in 30 days.
          Note as of rules_nodejs v6 the rules_nodejs repository contains only the core nodejs toolchain
          and `@bazel/runfiles` package. All rulesets are removed and unmaintained.
          For alternate rulesets suggestions include https://github.com/aspect-build/rules_js, https://github.com/aspect-build/rules_ts
          Collaborators can add a "cleanup" or "need: discussion" label to keep it open indefinitely.
          Thanks for your contributions to rules_nodejs!

        stale-pr-message: >
          This Pull Request has been automatically marked as stale because it has had no recent activity.
          It will be closed if no further activity occurs in 30 days.
          Collaborators can add a "cleanup" or "need: discussion" label to keep it open indefinitely.
          Thanks for your contributions to rules_nodejs!

        close-issue-message: >
          This issue was automatically closed because it went 30 days without any activity
          since it was labeled "Can Close?"

        close-pr-message: >
          This PR was automatically closed because it went 30 days without any activity
          since it was labeled "Can Close?"
