name: Update NodeJS Versions

on:
  # Trigger manually in the UI
  workflow_dispatch:
  schedule:
    # run at 01:30 UTC daily
    - cron: '30 1 * * *'

permissions:
  contents: read

jobs:
  updateNodejsVersions:
    runs-on: ubuntu-latest

    # Skip this on forks
    if: github.repository == 'bazelbuild/rules_nodejs'

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Run yarn update-nodejs-versions
        run: |
          yarn run update-nodejs-versions
          bazel run docs:update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update NodeJS Versions
          title: Update NodeJS Versions
          body: |
            - Updated NodeJS Versions using `yarn run update-nodejs-versions`

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-nodejs-versions
